backend:
  name: github
  repo: vags97/mural-boric
  branch: main
media_folder: "docs/.vuepress/public/media/afiches"
public_folder: "/media/afiches"
publish_mode: editorial_workflow
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "docs/index.md"
        delete: false
        fields:
          - { label: "Home", name: "home", widget: "hidden", default: true }
          - { label: "Titulo", name: "title", widget: "string" }
          - { label: "Imagen", name: "image", widget: "image", default: "/media/materiales/gabriel-boric.jpg" }
          - { label: "Descripción", name: "description", widget: "string" }
          - { label: "Tags", name: "tags", widget: "list", required: false }
          - { label: "Cuerpo", name: body, widget: markdown, required: false }
  - label: "Afiche"
    name: "materiales"
    folder: "docs/materiales"
    create: true
    media_folder: "../.vuepress/public/media/materiales"
    public_folder: "/media/materiales"
    fields:
      - { label: "Material", name: "materiales", widget: "hidden", default: true }
      - { label: "Titulo", name: "title", widget: "string", required: true }
      - { label: "Tags", name: "tags", widget: "list", required: false, default: ['Gabriel Boric'] }
      - { label: "Fecha", name: "date", widget: "date", hidden: true }
      - label: "Imagen"
        name: "image"
        widget: "image"
        required: true
        default: "/media/materiales/gabriel-boric.jpg"
      - { label: "Cuerpo", name: body, widget: markdown, required: false }
