backend:
  name: github
  repo: vags97/mural-boric
media_folder: "docs/.vuepress/public/media"
public_folder: "/media"
publish_mode: editorial_workflow
collections:
  - label: "Home"
    name: "home"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "docs/index.md"
        delete: false
        fields:
          - { label: "Home", name: "home", widget: "hidden", default: true }
          - { label: "Titulo", name: "title", widget: "string" }
          - { label: "Imagen", name: "image", widget: "image", default: "/media/gabriel-boric.jpg" }
          - { label: "Descripción", name: "description", widget: "string" }
          - { label: "Tags", name: "tags", widget: "list", required: false }
          - { label: "Cuerpo", name: body, widget: markdown, required: false }
  - label: "Material"
    name: "material"
    folder: "docs/materiales"
    create: true
    fields:
      - { label: "Material", name: "material", widget: "hidden", default: true }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false, default: ['Gabriel Boric'] }
      - { label: "Fecha", name: "date", widget: "date" }
      - label: "Imagen"
        name: "image"
        widget: "image"
        default: "/media/gabriel-boric.jpg"
        media_library:
          config:
            cloud_name: cloudnary
            multiple: true
      - label: "Archivo"
        name: "file"
        widget: "file"
        default: ""
        required: false
        media_library:
          config:
            cloud_name: cloudnary
            multiple: true
      - label: "Archivo de Descarga Externa (URL)"
        name: "file_external"
        widget: "string"
        default: ""
        required: false
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown", required: false }
